# Generated by Django 3.1 on 2020-11-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commande_date', models.DateField(blank=True, null=True, verbose_name='Date de commande')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_personne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('naissance_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('alimentation', models.TextField(blank=True, null=True, verbose_name='Alimentation')),
                ('medicament', models.TextField(blank=True, null=True, verbose_name='Médicament')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
        migrations.CreateModel(
            name='Service_Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service_produit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('type_service_produit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix')),
            ],
            options={
                'verbose_name': 'Service / Produit',
                'verbose_name_plural': 'Services / Produits',
            },
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrivee_date', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('depart_date', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('id_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sejour_id_commande', to='Senso_facturation_app.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Séjour',
                'verbose_name_plural': 'Séjours',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='id_personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commande_personne', to='Senso_facturation_app.personne', verbose_name='Personne'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_service_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commande_service_produit', to='Senso_facturation_app.service_produit', verbose_name='Service / Produit'),
        ),
    ]
