# Generated by Django 3.1 on 2020-11-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('adresse_client', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse')),
                ('mail_client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('telephone_client', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Dernier_Numero_Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facture_asso', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dernier numéro de facture Association')),
                ('facture_senso', models.IntegerField(blank=True, default=10000, null=True, verbose_name='Dernier numéro de facture Sensoryalis')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emetteur', models.CharField(choices=[('', ''), ('Asso', 'Association'), ('Senso', 'Sensoryalis')], default='', max_length=20, verbose_name='Emetteur de la facture')),
                ('numero_facture', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de la facture')),
                ('numero_commande', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de la commande')),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('nombre_jours', models.IntegerField(blank=True, null=True, verbose_name='Nombre de jours')),
                ('montant_paiement_arrhes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant des arrhes')),
                ('modes_paiement_arrhes', models.TextField(blank=True, null=True, verbose_name='Modes de paiement des arrhes')),
                ('date_paiement_arrhes', models.DateField(blank=True, null=True, verbose_name='Date de paiement des arrhes')),
                ('montant_paiement_solde', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant du solde')),
                ('modes_paiement_solde', models.TextField(blank=True, null=True, verbose_name='Modes de paiement du solde')),
                ('date_paiement_solde', models.DateField(blank=True, null=True, verbose_name='Date de paiement du solde')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Facture')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='Senso_facturation_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_personne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('prenom_personne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('adresse_personne', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse')),
                ('mail_personne', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('telephone_personne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('assujettie_taxe_sejour', models.BooleanField(blank=True, null=True, verbose_name='Assujettie à la taxe de séjour')),
                ('alimentation', models.TextField(blank=True, null=True, verbose_name='Alimentation')),
                ('medicament', models.TextField(blank=True, null=True, verbose_name='Médicament')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
        migrations.CreateModel(
            name='Service_Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service_produit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('type_service_produit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix Unitaire')),
            ],
            options={
                'verbose_name': 'Service/Produit',
                'verbose_name_plural': 'Services/Produits',
            },
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_taxe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('initiales', models.CharField(blank=True, max_length=10, null=True, verbose_name='Initiales')),
                ('type_taxe', models.CharField(choices=[('', ''), ('Taux_Sans_Mini', 'Taux sans minimum'), ('Taux_Avec_Mini_Global', 'Taux avec minimum global'), ('Taux_Avec_Mini_Par_Jour', 'Taux avec minimum par jour'), ('Montant_Fixe_Global', 'Montant fixe global'), ('Montant_Fixe_Par_Jour', 'Montant fixe par jour'), ('Type_Taxe_De_Sejour', 'Type taxe de séjour')], default='', max_length=30, verbose_name='Type de taxe')),
                ('taux', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Taux')),
                ('mini', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Minimal')),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Montant')),
            ],
            options={
                'verbose_name': 'Taxe',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='Taxe_Service_Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.service_produit', verbose_name='Service/produit')),
                ('taxe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.taxe', verbose_name='Taxe Service/Produit')),
            ],
            options={
                'verbose_name': 'Taxe/Service/produit',
                'verbose_name_plural': 'Taxes/Services/Produits',
            },
        ),
        migrations.AddField(
            model_name='taxe',
            name='services_produits',
            field=models.ManyToManyField(through='Senso_facturation_app.Taxe_Service_Produit', to='Senso_facturation_app.Service_Produit'),
        ),
        migrations.CreateModel(
            name='Service_Produit_Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('prix_total_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix Total HT')),
                ('remise', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Remise')),
                ('date_commande', models.DateField(blank=True, null=True, verbose_name='Date de commande')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.facture', verbose_name='Facture')),
                ('service_produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.service_produit', verbose_name='Service commandé')),
            ],
            options={
                'verbose_name': 'Service/Produit commandé',
                'verbose_name_plural': 'Services/Produits commandés',
            },
        ),
        migrations.AddField(
            model_name='service_produit',
            name='taxes',
            field=models.ManyToManyField(through='Senso_facturation_app.Taxe_Service_Produit', to='Senso_facturation_app.Taxe'),
        ),
        migrations.CreateModel(
            name='Personne_Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.facture', verbose_name='Facture')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.personne', verbose_name='Personne')),
            ],
            options={
                'verbose_name': 'Personne/Facture',
                'verbose_name_plural': 'Personnes/Factures',
            },
        ),
        migrations.AddField(
            model_name='personne',
            name='factures',
            field=models.ManyToManyField(through='Senso_facturation_app.Personne_Facture', to='Senso_facturation_app.Facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='personnes',
            field=models.ManyToManyField(through='Senso_facturation_app.Personne_Facture', to='Senso_facturation_app.Personne'),
        ),
    ]
