# Generated by Django 3.1 on 2020-11-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxe',
            name='type_taxe',
            field=models.CharField(choices=[('', ''), ('Taux_Sans_Mini', 'Taux sans minimum'), ('Taux_Avec_Mini_Par_Jour', 'Taux avec minimum par jour'), ('Taux_Avec_Mini_Global', 'Taux avec minimum global'), ('Montant_fixe_par_jour', 'Montant fixe par jour'), ('Montant_fixe_global', 'Montant fixe global'), ('Type_Taxe_De_Sejour', 'Type taxe de séjour')], default='', max_length=30, verbose_name='Type de taxe'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='Senso_facturation_app.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='personne_facture',
            name='id_facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.facture', verbose_name='Identifiant Facture'),
        ),
        migrations.AlterField(
            model_name='personne_facture',
            name='id_personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnes', to='Senso_facturation_app.personne', verbose_name='Identifiant Personne'),
        ),
        migrations.AlterField(
            model_name='service_produit_commande',
            name='id_facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='service_produit_commande',
            name='id_service_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='Senso_facturation_app.service_produit', verbose_name='Service commandé'),
        ),
        migrations.AlterField(
            model_name='taxe_service_produit',
            name='id_service_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='Senso_facturation_app.service_produit', verbose_name='Service/produit'),
        ),
        migrations.AlterField(
            model_name='taxe_service_produit',
            name='id_taxe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.taxe', verbose_name='Taxe Service/Produit'),
        ),
    ]
