# Generated by Django 3.1 on 2020-11-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_taxe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('taux', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Taux')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='arrhes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Arrhes'),
        ),
        migrations.AddField(
            model_name='service_produit',
            name='id_taxe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_produit_taxe', to='Senso_facturation_app.taxe', verbose_name='Taxe'),
        ),
    ]
