# Generated by Django 3.1 on 2020-11-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0002_auto_20201120_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='service_produit_commande',
            old_name='id_facture',
            new_name='facture',
        ),
        migrations.RenameField(
            model_name='taxe_service_produit',
            old_name='id_taxe',
            new_name='taxe',
        ),
        migrations.RemoveField(
            model_name='personne_facture',
            name='id_facture',
        ),
        migrations.RemoveField(
            model_name='personne_facture',
            name='id_personne',
        ),
        migrations.RemoveField(
            model_name='service_produit_commande',
            name='id_service_produit',
        ),
        migrations.RemoveField(
            model_name='taxe_service_produit',
            name='id_service_produit',
        ),
        migrations.AddField(
            model_name='facture',
            name='nombre_jours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de jours'),
        ),
        migrations.AddField(
            model_name='personne_facture',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.facture', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='personne_facture',
            name='personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.personne', verbose_name='Personne'),
        ),
        migrations.AddField(
            model_name='service_produit_commande',
            name='service_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.service_produit', verbose_name='Service commandé'),
        ),
        migrations.AddField(
            model_name='taxe_service_produit',
            name='service_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.service_produit', verbose_name='Service/produit'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='type_taxe',
            field=models.CharField(choices=[('', ''), ('Taux_Sans_Mini', 'Taux sans minimum'), ('Taux_Avec_Mini_Global', 'Taux avec minimum global'), ('Taux_Avec_Mini_Par_Jour', 'Taux avec minimum par jour'), ('Montant_Fixe_Global', 'Montant fixe global'), ('Montant_Fixe_Par_Jour', 'Montant fixe par jour'), ('Type_Taxe_De_Sejour', 'Type taxe de séjour')], default='', max_length=30, verbose_name='Type de taxe'),
        ),
    ]
