# Generated by Django 3.1 on 2020-11-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0002_auto_20201124_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='date_paiement_arrhes',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_paiement_solde',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='modes_paiement_arrhes',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='modes_paiement_solde',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_paiement_arrhes',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_paiement_solde',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='total',
        ),
        migrations.AlterField(
            model_name='service_produit_commande',
            name='service_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.service_produit', verbose_name='Service/Produit'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant_paiement_arrhes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant des arrhes')),
                ('montant_paiement_solde', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant du solde')),
                ('mode_paiement', models.TextField(blank=True, null=True, verbose_name='Mode de paiement')),
                ('numero_cheque', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro du chèque')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('service_produit_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='Senso_facturation_app.service_produit_commande', verbose_name='Service/Produit commandé')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
