# Generated by Django 3.1 on 2020-11-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0003_auto_20201126_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('', ''), ('Chèque', 'Chèque'), ('Chèques Vacances', 'Chèques Vacances'), ('Carte de Crédit', 'Carte de Crédit'), ('Carte Tickets Restaurant', 'Carte Tickets Restaurant'), ('Liquide', 'Liquide'), ('Tickets Restaurant', 'Tickets Restaurant'), ('Virement Bancaire', 'Virement Bancaire')], max_length=30, null=True, verbose_name='Mode de paiement'),
        ),
    ]
