# Generated by Django 3.1 on 2020-11-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0003_auto_20201120_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de la facture'),
        ),
    ]
