# Generated by Django 3.1 on 2020-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0004_auto_20201122_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='personnes',
            field=models.ManyToManyField(through='Senso_facturation_app.Personne_Facture', to='Senso_facturation_app.Personne'),
        ),
        migrations.AddField(
            model_name='facture',
            name='services_produits',
            field=models.ManyToManyField(through='Senso_facturation_app.Service_Produit_Commande', to='Senso_facturation_app.Service_Produit'),
        ),
        migrations.AddField(
            model_name='service_produit',
            name='taxes',
            field=models.ManyToManyField(through='Senso_facturation_app.Taxe_Service_Produit', to='Senso_facturation_app.Taxe'),
        ),
    ]
