# Generated by Django 3.1 on 2020-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0004_auto_20201126_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='montant_paiement_arrhes',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='montant_paiement_solde',
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_paiement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant du paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('', ''), ('Arrhes', 'Arrhes'), ('Solde', 'Solde')], default='', max_length=10, verbose_name='Type de paiement'),
        ),
    ]
