# Generated by Django 3.1 on 2020-11-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0005_auto_20201122_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='services_produits',
        ),
    ]
