# Generated by Django 3.1 on 2020-11-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0005_auto_20201130_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-numero_facture'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='service_produit',
            options={'ordering': ['nom_service_produit'], 'verbose_name': 'Service/Produit', 'verbose_name_plural': 'Services/Produits'},
        ),
        migrations.AlterModelOptions(
            name='service_produit_commande',
            options={'ordering': ['facture', 'service_produit'], 'verbose_name': 'Service/Produit commandé', 'verbose_name_plural': 'Services/Produits commandés'},
        ),
    ]
