# Generated by Django 3.1 on 2020-11-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0006_auto_20201123_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dernier_Numero_Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facture_asso', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dernier numéro de facture Association')),
                ('facture_senso', models.IntegerField(blank=True, default=10000, null=True, verbose_name='Dernier numéro de facture Sensoryalis')),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='dernier_numero_facture_asso',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='dernier_numero_facture_senso',
        ),
    ]
