# Generated by Django 3.1 on 2020-11-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0006_auto_20201130_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='emetteur',
            field=models.CharField(blank=True, choices=[('', ''), ('Asso', 'Association'), ('Senso', 'Sensoryalis')], default='', max_length=20, null=True, verbose_name='Emetteur de la facture'),
        ),
    ]
