# Generated by Django 3.1 on 2020-11-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0007_auto_20201130_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom_client'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ['nom_personne', 'prenom_personne'], 'verbose_name': 'Personne', 'verbose_name_plural': 'Personnes'},
        ),
        migrations.AlterModelOptions(
            name='service_produit_commande',
            options={'verbose_name': 'Service/Produit commandé', 'verbose_name_plural': 'Services/Produits commandés'},
        ),
        migrations.AlterModelOptions(
            name='taxe',
            options={'ordering': ['nom_taxe'], 'verbose_name': 'Taxe', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterModelOptions(
            name='taxe_service_produit',
            options={'ordering': ['service_produit', 'taxe'], 'verbose_name': 'Taxe/Service/produit', 'verbose_name_plural': 'Taxes/Services/Produits'},
        ),
    ]
