# Generated by Django 3.1 on 2020-11-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0007_auto_20201123_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Senso_facturation_app.client', verbose_name='Client'),
        ),
    ]
