# Generated by Django 3.1 on 2020-11-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0008_auto_20201130_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_produit',
            options={'ordering': ['type_service_produit', 'nom_service_produit'], 'verbose_name': 'Service/Produit', 'verbose_name_plural': 'Services/Produits'},
        ),
    ]
