# Generated by Django 3.1 on 2020-11-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0008_auto_20201124_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='factures',
            field=models.ManyToManyField(through='Senso_facturation_app.Personne_Facture', to='Senso_facturation_app.Facture'),
        ),
        migrations.AddField(
            model_name='taxe',
            name='services_produits',
            field=models.ManyToManyField(through='Senso_facturation_app.Taxe_Service_Produit', to='Senso_facturation_app.Service_Produit'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='Senso_facturation_app.client', verbose_name='Client'),
        ),
    ]
