# Generated by Django 3.1 on 2020-11-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0009_auto_20201124_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='factures',
        ),
        migrations.RemoveField(
            model_name='taxe',
            name='services_produits',
        ),
    ]
