# Generated by Django 3.1 on 2020-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0009_auto_20201130_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom_client',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='service_produit',
            name='nom_service_produit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='nom_taxe',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='personne',
            unique_together={('nom_personne', 'prenom_personne')},
        ),
    ]
