# Generated by Django 3.1 on 2020-11-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senso_facturation_app', '0010_auto_20201130_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom_client',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom_personne',
            field=models.CharField(default='', max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='prenom_personne',
            field=models.CharField(default='', max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='service_produit',
            name='nom_service_produit',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='service_produit',
            name='type_service_produit',
            field=models.CharField(default='', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='initiales',
            field=models.CharField(default='', max_length=10, verbose_name='Initiales'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='nom_taxe',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
